"""add_game_items_count_fields

Revision ID: 4ffb5d003aa2
Revises: c89dc93fd5e9
Create Date: 2026-01-14 22:26:53.437410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffb5d003aa2'
down_revision: Union[str, Sequence[str], None] = 'c89dc93fd5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('difficulties', sa.Column('game_items_count_default', sa.Integer(), nullable=True))
    op.add_column('game_rules', sa.Column('game_items_count', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('game_rules_row_count_col_count_target_score_is_one_swap_mod_key'), 'game_rules', type_='unique')
    op.create_unique_constraint(None, 'game_rules', ['row_count', 'col_count', 'target_score', 'is_one_swap_mode', 'is_one_item_mode', 'game_items_count'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_rules', type_='unique')
    op.create_unique_constraint(op.f('game_rules_row_count_col_count_target_score_is_one_swap_mod_key'), 'game_rules', ['row_count', 'col_count', 'target_score', 'is_one_swap_mode', 'is_one_item_mode'], postgresql_nulls_not_distinct=False)
    op.drop_column('game_rules', 'game_items_count')
    op.drop_column('difficulties', 'game_items_count_default')
    # ### end Alembic commands ###
