"""New revision

Revision ID: 58fc84e58aa8
Revises: 8a1ee694c1e3
Create Date: 2025-12-10 22:15:14.945806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fc84e58aa8'
down_revision: Union[str, Sequence[str], None] = '8a1ee694c1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('difficulties', 'row_count_default',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('difficulties', 'col_count_default',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('difficulties', 'target_score_default',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('difficulties', 'is_one_swap_mode_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('difficulties', 'is_one_item_mode_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('difficulties', 'is_one_item_mode_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('difficulties', 'is_one_swap_mode_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('difficulties', 'target_score_default',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('difficulties', 'col_count_default',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('difficulties', 'row_count_default',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
