"""Initial revision

Revision ID: 8a1ee694c1e3
Revises: 
Create Date: 2025-12-10 02:51:10.352461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1ee694c1e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulties',
    sa.Column('difficulty_name', sa.String(), nullable=False),
    sa.Column('row_count_default', sa.Integer(), nullable=False),
    sa.Column('col_count_default', sa.Integer(), nullable=False),
    sa.Column('target_score_default', sa.Integer(), nullable=False),
    sa.Column('is_one_swap_mode_default', sa.Boolean(), nullable=False),
    sa.Column('is_one_item_mode_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('difficulty_name')
    )
    op.create_index(op.f('ix_difficulties_id'), 'difficulties', ['id'], unique=False)
    op.create_table('game_fields',
    sa.Column('field', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_fields_id'), 'game_fields', ['id'], unique=False)
    op.create_table('game_rules',
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('col_count', sa.Integer(), nullable=False),
    sa.Column('target_score', sa.Integer(), nullable=False),
    sa.Column('is_one_swap_mode', sa.Boolean(), nullable=False),
    sa.Column('is_one_item_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_count', 'col_count', 'target_score', 'is_one_swap_mode', 'is_one_item_mode')
    )
    op.create_index(op.f('ix_game_rules_id'), 'game_rules', ['id'], unique=False)
    op.create_table('games',
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('game_rule_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('last_action_time', sa.DateTime(), nullable=True),
    sa.Column('is_over', sa.Boolean(), nullable=False),
    sa.Column('lost_of_time', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulties.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['game_fields.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_rule_id'], ['game_rules.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_game_rules_id'), table_name='game_rules')
    op.drop_table('game_rules')
    op.drop_index(op.f('ix_game_fields_id'), table_name='game_fields')
    op.drop_table('game_fields')
    op.drop_index(op.f('ix_difficulties_id'), table_name='difficulties')
    op.drop_table('difficulties')
    # ### end Alembic commands ###
