"""changed_nullable_option_of_game_items_count_in_game_rules_table

Revision ID: 9a1f44b54738
Revises: 4ffb5d003aa2
Create Date: 2026-01-14 22:39:45.978451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1f44b54738'
down_revision: Union[str, Sequence[str], None] = '4ffb5d003aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE game_rules SET game_items_count = 6 WHERE game_items_count IS NULL")
    op.execute("UPDATE difficulties SET game_items_count_default = 6 WHERE difficulty_name IN ('Простой', 'Средний', 'Сложный')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_rules', 'game_items_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE game_rules SET game_items_count = NULL WHERE game_items_count IS NOT NULL")
    op.execute(
        "UPDATE difficulties SET game_items_count_default = NULL WHERE difficulty_name IN ('Простой', 'Средний', 'Сложный')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_rules', 'game_items_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
